name: Deploy

on:
  push:
    branches: ["main"]
    paths:
      - 'apps/commands/**'

jobs:
  build:
      name: Deploy application commands to discord
      timeout-minutes: 15
      runs-on: ubuntu-latest
      strategy:
        matrix:
          node-version: [16.x]

      steps:
        - name: Check out code
          uses: actions/checkout@v2
          with:
            fetch-depth: 2

        - name: Setup Node.js environment
          uses: actions/setup-node@v2
          with:
            node-version: 16
            cache: 'yarn'

        - name: Install dependencies
          run: yarn

        - name: Deploy
          run: yarn deploy
          env:
            APP_ID: ${{ secrets.APP_ID }}
            GUILD_ID: ${{ secrets.GUILD_ID }}
            BOT_TOKEN: ${{ secrets.BOT_TOKEN }}