name: CI

on:
  push:
    branches: ["main"]

jobs:
  build:
      name: Build and Test
      timeout-minutes: 15
      steps:
        - name: Check out code
          uses: actions/checkout@v2
          with:
            fetch-depth: 2

        - name: Setup Node.js environment
          uses: actions/setup-node@v2
          with:
            node-version: 16
            cache: 'yarn'

        - name: Install dependencies
          run: yarn

        - name: Deploy
          run: yarn deploy